import type { VaultItem, Board, Alert } from "@/stores/vault-store"

export const INTERESTS = [
  { id: "fashion", emoji: "👗", label: "Fashion" },
  { id: "home", emoji: "🏡", label: "Home" },
  { id: "tech", emoji: "⚡", label: "Tech" },
  { id: "beauty", emoji: "💄", label: "Beauty" },
  { id: "travel", emoji: "✈️", label: "Travel" },
  { id: "food", emoji: "🍕", label: "Food" },
  { id: "fitness", emoji: "💪", label: "Fitness" },
  { id: "art", emoji: "🎨", label: "Art" },
  { id: "books", emoji: "📚", label: "Books" },
] as const

export const TESTIMONIALS = [
  {
    author: "Sarah M.",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    text: "I used to have 400+ product screenshots buried in my camera roll. VAULTED found and organized every single one in under 3 minutes.",
  },
  {
    author: "Jake L.",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    text: "The price drop alerts alone saved me $230 last month. This app pays for itself.",
  },
  {
    author: "Mia C.",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    text: "I made a moodboard for my apartment renovation and VAULTED suggested 4 items that perfectly completed the look. It gets me.",
  },
  {
    author: "David K.",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    text: "Finally an app that lets me screenshot from TikTok and actually find where to buy the thing.",
  },
  {
    author: "Emma R.",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    text: "My friends and I use collaborative boards to plan trips. It's like Pinterest but it actually works.",
  },
  {
    author: "Chris P.",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    text: "The Dupe Finder found me a $45 version of a $380 designer bag. Literally the same look. I'm obsessed.",
  },
  {
    author: "Priya S.",
    avatar: "https://randomuser.me/api/portraits/women/90.jpg",
    text: "I screenshot everything. Outfits, furniture, skincare. VAULTED turned my chaos into the most satisfying organized collection.",
  },
  {
    author: "Tom H.",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    text: "Used the gift intelligence feature for my wife's birthday. Best gift I've ever given her. She thinks I'm suddenly thoughtful.",
  },
  {
    author: "Lina W.",
    avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    text: "Black Friday was a breeze. VAULTED tracked 23 items and alerted me the second each one dropped. Saved over $400.",
  },
]

export const MOCK_ITEMS: VaultItem[] = [
  {
    id: "1",
    name: "Air Max 90",
    brand: "Nike",
    price: 89,
    originalPrice: 120,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    category: "Fashion",
    tags: ["sneakers", "white", "leather"],
    retailer: "Nike.com",
    retailerUrl: "https://nike.com",
    priority: 3,
    priceHistory: [
      { date: "2026-03-01", price: 120 },
      { date: "2026-03-05", price: 110 },
      { date: "2026-03-10", price: 95 },
      { date: "2026-03-15", price: 89 },
    ],
    priceStatus: "dropped",
    dateAdded: "2026-03-01",
    notes: "",
    boardIds: ["1"],
    isPurchased: false,
  },
  {
    id: "2",
    name: "Ceramic Table Lamp",
    brand: "CB2",
    price: 149,
    originalPrice: 199,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1655151418942-2bf9df1cfdf3?q=80&w=1261&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Home",
    tags: ["lamp", "ceramic", "modern"],
    retailer: "CB2",
    retailerUrl: "https://cb2.com",
    priority: 2,
    priceHistory: [
      { date: "2026-03-01", price: 199 },
      { date: "2026-03-08", price: 179 },
      { date: "2026-03-15", price: 149 },
    ],
    priceStatus: "dropped",
    dateAdded: "2026-02-28",
    notes: "For the living room",
    boardIds: ["2"],
    isPurchased: false,
  },
  {
    id: "3",
    name: "Leather Crossbody Bag",
    brand: "Madewell",
    price: 168,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop",
    category: "Fashion",
    tags: ["bag", "leather", "brown"],
    retailer: "Madewell",
    retailerUrl: "https://madewell.com",
    priority: 2,
    priceHistory: [
      { date: "2026-03-01", price: 168 },
      { date: "2026-03-15", price: 168 },
    ],
    priceStatus: "stable",
    dateAdded: "2026-03-02",
    notes: "",
    boardIds: [],
    isPurchased: false,
  },
  {
    id: "4",
    name: "AirPods Pro 2",
    brand: "Apple",
    price: 199,
    originalPrice: 249,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    category: "Tech",
    tags: ["earbuds", "wireless", "noise-cancelling"],
    retailer: "Amazon",
    retailerUrl: "https://amazon.com",
    priority: 3,
    priceHistory: [
      { date: "2026-02-20", price: 249 },
      { date: "2026-03-01", price: 229 },
      { date: "2026-03-10", price: 199 },
    ],
    priceStatus: "best",
    dateAdded: "2026-02-20",
    notes: "Best price ever!",
    boardIds: ["3"],
    isPurchased: false,
  },
  {
    id: "5",
    name: "Linen Duvet Cover Set",
    brand: "Brooklinen",
    price: 289,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=400&fit=crop",
    category: "Home",
    tags: ["bedding", "linen", "white"],
    retailer: "Brooklinen",
    retailerUrl: "https://brooklinen.com",
    priority: 1,
    priceHistory: [
      { date: "2026-03-01", price: 289 },
      { date: "2026-03-15", price: 289 },
    ],
    priceStatus: "stable",
    dateAdded: "2026-03-05",
    notes: "",
    boardIds: ["2"],
    isPurchased: false,
  },
  {
    id: "6",
    name: "Retinol Serum 1%",
    brand: "The Ordinary",
    price: 8.5,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
    category: "Beauty",
    tags: ["skincare", "serum", "retinol"],
    retailer: "Sephora",
    retailerUrl: "https://sephora.com",
    priority: 2,
    priceHistory: [{ date: "2026-03-10", price: 8.5 }],
    priceStatus: "stable",
    dateAdded: "2026-03-10",
    notes: "",
    boardIds: [],
    isPurchased: false,
  },
  {
    id: "7",
    name: "Wool Overcoat",
    brand: "COS",
    price: 250,
    originalPrice: 350,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400&h=400&fit=crop",
    category: "Fashion",
    tags: ["coat", "wool", "black", "winter"],
    retailer: "COS",
    retailerUrl: "https://cos.com",
    priority: 3,
    priceHistory: [
      { date: "2026-02-15", price: 350 },
      { date: "2026-03-01", price: 300 },
      { date: "2026-03-12", price: 250 },
    ],
    priceStatus: "dropped",
    dateAdded: "2026-02-15",
    notes: "End of season sale",
    boardIds: ["1"],
    isPurchased: false,
  },
  {
    id: "8",
    name: "Minimalist Desk Lamp",
    brand: "Muji",
    price: 79,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1534105615256-13940a56ff44?w=400&h=400&fit=crop",
    category: "Home",
    tags: ["lamp", "desk", "minimalist"],
    retailer: "Muji",
    retailerUrl: "https://muji.com",
    priority: 1,
    priceHistory: [{ date: "2026-03-08", price: 79 }],
    priceStatus: "stable",
    dateAdded: "2026-03-08",
    notes: "",
    boardIds: ["2"],
    isPurchased: false,
  },
]

export const MOCK_BOARDS: Board[] = [
  {
    id: "1",
    name: "Fall Wardrobe",
    description: "Autumn essentials",
    coverImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=300&fit=crop",
    type: "standard",
    itemIds: ["1", "3", "7"],
    isPublic: false,
    createdAt: "2026-02-15",
  },
  {
    id: "2",
    name: "Apartment Refresh",
    description: "Living room makeover",
    coverImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop",
    type: "moodboard",
    itemIds: ["2", "5", "8"],
    isPublic: true,
    createdAt: "2026-02-28",
  },
  {
    id: "3",
    name: "Tech Upgrades",
    description: "Gadgets I need",
    coverImage: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&h=300&fit=crop",
    type: "standard",
    itemIds: ["4"],
    isPublic: false,
    createdAt: "2026-03-01",
  },
]

export const MOCK_ALERTS: Alert[] = [
  {
    id: "1",
    type: "price_drop",
    title: "Price Drop!",
    description: "Nike Air Max 90 dropped from $120 to $89 — that's 26% off!",
    itemId: "1",
    read: false,
    createdAt: "2026-03-15T08:30:00Z",
  },
  {
    id: "2",
    type: "low_stock",
    title: "Low Stock Warning",
    description: "Ceramic Table Lamp (CB2) — Only 2 left in stock!",
    itemId: "2",
    read: false,
    createdAt: "2026-03-15T06:00:00Z",
  },
  {
    id: "3",
    type: "suggestion",
    title: "Complete the Look",
    description:
      "Based on your Fall Wardrobe board, these boots would pair perfectly with your wool overcoat.",
    read: true,
    createdAt: "2026-03-14T14:00:00Z",
  },
  {
    id: "4",
    type: "weekly_summary",
    title: "Your Week in Review",
    description: "Saved: 8 items | Price Drops: 3 | Total Savings: $145.20",
    read: true,
    createdAt: "2026-03-14T09:00:00Z",
  },
]

export const PRICING_PLANS = [
  {
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: [
      "50 items",
      "5 boards",
      "20 AI scans/month",
      "Daily price checks",
      "Share wishlists",
    ],
  },
  {
    name: "Premium",
    monthlyPrice: 9.99,
    yearlyPrice: 79.99,
    popular: true,
    features: [
      "Unlimited items & boards",
      "Unlimited AI scans",
      "6-hourly price checks",
      "Dupe Finder",
      "Cross-retailer comparison",
      "AI moodboards",
      "Gift Intelligence",
      "Budget Guardian",
      "Style Engine",
      "Browser extension",
      "Watermark-free exports",
    ],
  },
  {
    name: "Vault Family",
    monthlyPrice: 14.99,
    yearlyPrice: 119.99,
    features: [
      "Everything in Premium",
      "Up to 5 family members",
      "Shared family boards",
      "Family gift coordinator",
      "Family budget dashboard",
    ],
  },
]
